# Generated by Django 4.2.7 on 2023-12-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_keep_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.TextField(primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
                ('inactive_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_expire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_key',
        ),
    ]
