# Generated by Django 5.0.3 on 2024-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customsession_remove_user_session_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
