# Generated by Django 5.0.3 on 2024-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customsession_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session_key',
            field=models.TextField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
