# Generated by Django 4.2.7 on 2023-11-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_number', models.CharField(max_length=25, unique=True)),
                ('is_subscriber', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
